In [1]:
import torch

In [6]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x)
print(x[:, None])
print(x.shape)
print(x[:, None, :].shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]])
torch.Size([2, 3])
torch.Size([2, 1, 3])


In [10]:
import torch
from torch import nn

In [7]:
x = torch.arange(0, 5).unsqueeze(-1).expand(-1, 5)
y = x + torch.zeros(size=(1, 5, 5))
y

tensor([[[0., 0., 0., 0., 0.],
         [1., 1., 1., 1., 1.],
         [2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3.],
         [4., 4., 4., 4., 4.]]])

In [ ]:
class T(nn.Module):
    def __init__(self):
        super(T, self).__init__()
        self.p = nn.Linear(3, 3)

    def forward(self, x, u = False):
        if u:
            return self.p(x)
        else:
            return self.p(x)
        
t = T()
i = torch.tensor([[1, 2, 3], [1, 2, 3], [1, 2, 3]], dtype=torch.float32)
o = t(i)
o2 = t(i, u=True)

print(o)
print(o2)


tensor([[ 2.1166, -0.5609, -0.8280],
        [ 2.1166, -0.5609, -0.8280],
        [ 2.1166, -0.5609, -0.8280]], grad_fn=<AddmmBackward0>)
tensor([[ 2.1166, -0.5609, -0.8280],
        [ 2.1166, -0.5609, -0.8280],
        [ 2.1166, -0.5609, -0.8280]], grad_fn=<AddmmBackward0>)


In [20]:
x = torch.randn((4,3))
x

tensor([[-2.1835, -0.3046, -1.9750],
        [-0.4985,  1.9430,  0.8169],
        [-0.6055, -1.3937, -0.3138],
        [-0.9487, -0.1477,  0.2778]])

In [21]:
x = x.reshape(2, 2, -1)
x

tensor([[[-2.1835, -0.3046, -1.9750],
         [-0.4985,  1.9430,  0.8169]],

        [[-0.6055, -1.3937, -0.3138],
         [-0.9487, -0.1477,  0.2778]]])

In [29]:
a = torch.tensor([1., 2., 3., 4., 5., 6., 7., 8., 9., 10.])
a = a.reshape(5, 2).unsqueeze(-1)
b = torch.randn((5, 2, 2))
b @ a

tensor([[[ -1.0685],
         [ -2.8802]],

        [[  7.3790],
         [  3.6900]],

        [[  2.4330],
         [  0.1179]],

        [[ -6.8593],
         [ -0.2692]],

        [[  2.2953],
         [-33.6595]]])